ktor:
  application:
    modules:
      - ru.alex009.ApplicationKt.module
  deployment:
    port: 8000
jwt:
  keycloak:
    url: "$KEYCLOAK_URL:http://localhost.proxyman.io:8080"
    realm: "$KEYCLOAK_REALM:reports-realm"
    issuer: "$KEYCLOAK_ISSUER:http://localhost.proxyman.io:8080/realms/reports-realm"
